### ISSUE TITLE
Calendar Selection for Events Screen

### ISSUE THREAD

**Issue by tajetaje** [UKDanceBlue/danceblue-react-app#130]
**Is your feature request related to a problem? Please describe.**
Right now, our events page is not the cleanest or prettiest, as this is going to be a high traffic part of the app, we need to get it in better condition.

**Describe the solution you'd like**
Kind of emulating some similar apps, it would be cool to have a calendar view at the top with a cleaner list below it. This will require reworking the way the page downloads the list of events from firebase, and how it sorts/displays them. In addition, the EventRow component will need to be upgraded so it looks a bit better.

**Additional context**
I think [React Native Calendars](https://www.npmjs.com/package/react-native-calendars) would be best for the actual date picker at the top

**Comment by Jacksonnnnn** [comment]
Attached below is the proposed layout. From our meeting notes:

- We will probably have to come back to this page to make sure it fits the theme of the rest of the app redesign. The main priority for the Events Page is to get the Backend and general setup settled.

![Image](https://user-images.githubusercontent.com/12401685/202048130-b4fe25b4-db86-45bb-b635-801fae65e3a1.png)
