### ISSUE TITLE
Integrate NativeBase theming

### ISSUE THREAD

**Issue by tajetaje** [UKDanceBlue/danceblue-react-app#131]
There is a LOT of inline styling done in the app (i.e. setting the style prop of a text component to change its font size). This is a big issue because not only does it make the code harder to read, it also makes our UI less consistent and harder to reuse. NativeBase (our UI library) does have a solution for this called theming, but up until now it has not been a priority. You can see NativeBase's [default theme](https://docs.nativebase.io/default-theme) on their website for a basic example. There are two big priorities for our theme work. We need to update the [color scheme](https://docs.nativebase.io/customizing-theme) and create a bunch of [variants](https://docs.nativebase.io/customizing-components) for common components so we can reuse styles and change them all in one place, though it would be nice to support [dark mode](https://docs.nativebase.io/dark-mode) too (not a priority though).

**Comment by tajetaje** [comment]
We will also want to set up some prefab variants of common components, a few that come to mind are:

- Headers
- Text blocks (underline, italic, emphasis, etc.)
- Links vs buttons
- Common layout configurations
- Image boxes

**Comment by tajetaje** [comment]
I have created a branch with a basis for you to build on, see `src/theme` on #156. It's mostly just the default theme copied into the project so you can work with it easily, there are a few properties I didn't stub out but feel free to add them if you like.

**Comment by Jacksonnnnn** [comment]
Attached are the components I am working on (completed and todo) as well as their original idea from the design and page implementation(s):

- ### AboutItem
Page(s): About Us
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213549866-31db9f84-02aa-465f-9e0c-86cba937f052.png)

- ### Breadcrumbs
Page(s): All Pages (except Home Page)
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213550900-b319ae66-30ca-470c-b5ee-e6a475f30688.png)

- ### Button
Page(s): idk
Reference: 
![Image](https://user-images.githubusercontent.com/12401685/213551048-95c52646-3eaa-4015-919f-a507c7369c8a.png)
![Image](https://user-images.githubusercontent.com/12401685/213551083-61b5632e-b987-46f7-90c5-12f8e203df91.png)

- ### FAQItem
Page(s): FAQ
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551181-a1ff6307-4ed9-48e7-b3b0-056a45f6e3dd.png)

- ### FeedBlog
Page(s): Explorer
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551267-e903e3a4-8899-41b2-a583-8344568598fe.png)

- ### FeedInstagram
Page(s): Explorer
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551336-915e18f2-5e75-40ea-b9a4-8204bc4b2f7f.png)

- ### FeedTwitter
Page(s): Explorer
Reference: None

- ### JumbotronGeneral
Page(s): Scoreboard
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551421-ad966a6b-732a-427d-856a-8e38f577e6b8.png)

- ### JumbotronWelcome
Page(s): Notifications / Profile
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551546-f1537542-a9ef-44d7-b962-6b3a2e905e48.png)

- ### Notification
Page(s): Notifications / TeamDashboard
Reference: 
![Image](https://user-images.githubusercontent.com/12401685/213551672-31b59687-0d09-47dd-b2b9-47bd3c775005.png)
![Image](https://user-images.githubusercontent.com/12401685/213551691-0312b8eb-40ef-458a-912e-d4d906d56eff.png)

- ### Scoreboard
Page(s): Scoreboard
Notes: Need to install LeagueSpartan font for numbering
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213551881-98c6e70a-3b0c-4e37-80de-aff39cdb96cc.png)

- ### SponsorBlock (SponsorCard)
Page(s): Sponsors
Note(s): This is completed but this needs to be implemented as just SponsorCard so the data will be wrapped in the actual Sponsor's Page
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213552013-1e3e1f72-16d6-409b-9f45-b19b1d9cf6c5.png)

- ### TeamInformation
Page(s): TeamDashboard
Reference: ![Image](https://user-images.githubusercontent.com/12401685/213552112-89d5c311-cf85-4a59-9a1f-884e138ade25.png)
