### ISSUE TITLE
Redesign the Team Screen

### ISSUE THREAD

**Issue by jthoward64** [UKDanceBlue/danceblue-react-app#134]
**Is your feature request related to a problem? Please describe.**
Right now, the team screen is little more than a list of people and spirit points, and an ugly one at that.

**Describe the solution you'd like**
We should show team captains, the team's grand total, maybe a banner set by the captain, fundraising total, a nicer list, etc.

**Describe alternatives you've considered**
We could have a message board (but that could be costly in terms of database costs, so I don't think it'll happen) for the team captains to communicate with teams. Maybe have a way to see a list of upcoming events associated with your team?

**Additional context**
Also see #133

**Comment by Jacksonnnnn** [comment]
@tajetaje Here is a proposed design that I made in conjunction with one of the Graphic Design Coordinators:

![Image](https://user-images.githubusercontent.com/12401685/203368400-e350f544-77db-46dc-a0a1-311278868bfa.png)

**Comment by tajetaje** [comment]
I love the design, I will say though is that I'm not sure about adding our own back button there. Take a look at the presentation of the current notifications or profile screen/click on an event in the events list.

**Comment by tajetaje** [comment]
Made branch, it has a new navigator that will allow you to make the design you want here. I haven't tested it yet so it is almost certainly broken.

**Comment by jphuse** [comment]
Team Information need's to be fixed
