### ISSUE TITLE
Leaderboard Redesign

### ISSUE THREAD

**Issue by tajetaje** [UKDanceBlue/danceblue-react-app#147]

**Comment by Jacksonnnnn** [comment]
Attached below is the proposed redesign. From our meeting notes:

**Team Dashboard Pathway:**
- This would be the first page of the Teams page, which presents a scoreboard of spirit points as well as a path to the Team Dashboard if the app user is a part of a team.
    - The pathway in the proposed design would be a header "jumbotron" box at the top of the page. The first attached image shows the proposed design with no associated team attached to the user whereas the second one shows the proposed design when the user is apart of a team.

**Scoreboard/Leaderboard:**
- Need to decide if it will be called a Scoreboard or Leaderboard. The app shows Scoreboard currently.
- For the Scoreboard, the top three would get a medal as shown in the design, the place counting would begin at 4 after first, second, and third place.
- Each team gets a DB ribbon before their team name is displayed.
- The team name is presented in a Bolder weight of the same font that the points are presented on the right side.
- Points would be right justified, team name would be left justified starting at the ribbon.

![Image](https://user-images.githubusercontent.com/12401685/202050715-764f6fbf-272a-4de1-a44b-1872eef8b12d.png)
![Image](https://user-images.githubusercontent.com/12401685/202050716-1cbe73e8-34cb-461a-b438-6187d2a0c0a1.png)

**Comment by tajetaje** [comment]
I think leaderboard does sound better if it's not gonna be the name of the whole page. Will need to talk to DR about whether we want to show teams who have 0 points on the list at all

**Comment by tajetaje** [comment]
Made branch, it has a new navigator that will allow you to make the design you want here. I haven't tested it yet so it is almost certainly broken.
