### ISSUE TITLE
Login Screen Redesign

### ISSUE THREAD

**Issue by tajetaje** [UKDanceBlue/danceblue-react-app#148]

**Comment by Jacksonnnnn** [comment]
Attached below if the proposed redesign. From our meeting notes:

- We were discussing if it would be possible to do a slight animation after the app loads to get into the login screen. This is kinda easy with Canva and the idea would be that we would have a minimal-sized GIF or MP4 that plays after the app loads to transition from the loading screen into the login screen.
- The image, we discussed, would update from somewhere throughout the year, maybe RSS feed? What would that be pulled from? Or would we rather just update the app before/after an event with something? Could we just have a handful of pictures that it randomly selects on login or would that be too much?


![Image](https://user-images.githubusercontent.com/12401685/202048393-6fa64169-31aa-438f-9d5e-7e10566ec219.png)

**Comment by tajetaje** [comment]
Image for the login screen could easily be defined in Firestore, or we could just have a literal path in Firebase storage where the image gets replaced when we want it to.

**Comment by tajetaje** [comment]
I think there are probably two way to handle a transition like that, the first is something like the [Shared Element](https://docs.expo.dev/versions/v47.0.0/sdk/shared-element/) library, we could use React Native's [Animated](https://reactnative.dev/docs/animations) API, or the [Reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/animations) library (a replacement for the default API). If all else fails or we want something simple, there is always React Navigation's built-in [modal animation](https://reactnavigation.org/docs/modal).

There is also [this](https://github.com/fram-x/FluidTransitions) which seems like somewhere between React Navigation and Shared Component.

**Comment by tajetaje** [comment]
I created a branch for this issue but no PR yet
