### ISSUE TITLE
Profile Page Redesign

### ISSUE THREAD

**Issue by tajetaje** [UKDanceBlue/danceblue-react-app#149]

**Comment by Jacksonnnnn** [comment]
Attached below is the proposed redesign. From our meeting notes:

- The background graphic needs to be redesigned for better readability and coherence. Ideally, the graphic would be similar to the proposed design with a geometric background.

- The "Hey {name}!" would only be the first name.

- The Spirit Point Count and Donation Count sections is how many points and donations they have raised individually. The team contribution would be on the Team's Dashboard Page.

![Image](https://user-images.githubusercontent.com/12401685/202050326-981114d9-7af2-4c1f-8ef6-7c1f092b177c.png)

**Comment by tajetaje** [comment]
If the background graphic is gonna be geometric we should try and get it as an SVG or convert it to one if we get it as a raster (PNG/JPEG/etc)

**Comment by Jacksonnnnn** [comment]
@tajetaje I will get it in an SVG form and append it to this thread.

**Comment by Jacksonnnnn** [comment]
(PNG)
![Image](https://user-images.githubusercontent.com/12401685/203368028-8c70dfdc-65f3-4e8e-9ad4-c9c218372056.png)
(SVG)
![Image](https://user-images.githubusercontent.com/12401685/203368029-60960d9c-4591-471a-bb02-24e82f49cdbb.svg)

**Comment by tajetaje** [comment]
To future me or anyone else: DO NOT use that PNG directly, it is a 5K image which is like 50x the resolution of the best phones on the market, downscale it or use the SVG.

**Comment by tajetaje** [comment]
I created a branch for this issue but no PR yet

**Comment by tajetaje** [comment]
> (PNG) ![Image](https://user-images.githubusercontent.com/12401685/203368028-8c70dfdc-65f3-4e8e-9ad4-c9c218372056.png) (SVG) ![Image](https://user-images.githubusercontent.com/12401685/203368029-60960d9c-4591-471a-bb02-24e82f49cdbb.svg)

Something about how that SVG was made is making React Native angry so either we try a different image or we include [multiple PNGs](https://reactnative.dev/docs/images#static-image-resources). I'll keep messing around with it though
