### ISSUE TITLE
About/Sponsors/Other Page

### ISSUE THREAD

**Issue by jphuse** [UKDanceBlue/danceblue-react-app#152]

**Comment by tajetaje** [comment]
This could also be a handy place to throw some "useful resources", i.e. team captain vs team member vs committee member specific links (determined by the logged in user)

**Comment by tajetaje** [comment]
Contract with the sponsors says that the one's who have a logo on the website need to have logos on the home page of the app. my proposed solution is to keep the list of names in the about page and throw logos into the home feed randomly (ad style),
